import { PublicKey } from '@solana/web3.js';

export const ZK_ELGAMAL_PROOF_PROGRAM_ID = new PublicKey('ZkE1Gama1Proof11111111111111111111111111111');

export const ZERO_CIPHERTEXT_CONTEXT_ACCOUNT_SIZE = 129;
export const CIPHERTEXT_CIPHERTEXT_EQUALITY_CONTEXT_ACCOUNT_SIZE = 225;
export const CIPHERTEXT_COMMITMENT_EQUALITY_CONTEXT_ACCOUNT_SIZE = 161;
export const PUBKEY_VALIDITY_CONTEXT_ACCOUNT_SIZE = 65;
export const PERCENTAGE_WITH_CAP_CONTEXT_ACCOUNT_SIZE = 137;
export const BATCHED_RANGE_PROOF_CONTEXT_ACCOUNT_SIZE = 297;
export const GROUPED_CIPHERTEXT_2_HANDLES_VALIDITY_CONTEXT_ACCOUNT_SIZE = 193;
export const BATCHED_GROUPED_CIPHERTEXT_2_HANDLES_VALIDITY_CONTEXT_ACCOUNT_SIZE = 289;
export const GROUPED_CIPHERTEXT_3_HANDLES_VALIDITY_CONTEXT_ACCOUNT_SIZE = 257;
export const BATCHED_GROUPED_CIPHERTEXT_3_HANDLES_VALIDITY_CONTEXT_ACCOUNT_SIZE = 385;
