name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: >
      github.actor == 'dependabot[bot]' &&
      github.repository_owner == 'solana-program' &&
      !contains(github.event.pull_request.title, 'aes-gcm-siv') &&
      !contains(github.event.pull_request.title, 'curve25519-dalek') &&
      !contains(github.event.pull_request.title, 'sha3')

    steps:
      - name: Enable auto-merge for non-critical dependencies
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
